"""empty message

Revision ID: 1f3fe0ce39ff
Revises: 
Create Date: 2018-04-22 02:12:04.777572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3fe0ce39ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(length=16), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_address_postcode'), 'address', ['postcode'], unique=False)
    op.create_table('company',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('passhash', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('opening', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_company_cnpj'), 'company', ['cnpj'], unique=True)
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    op.create_table('item',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('fragile', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('compan_addr_relat',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('company_uid', sa.Integer(), nullable=False),
    sa.Column('address_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_uid'], ['address.uid'], ),
    sa.ForeignKeyConstraint(['company_uid'], ['company.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('proposal',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('destination', sa.Integer(), nullable=False),
    sa.Column('company_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_uid'], ['company.uid'], ),
    sa.ForeignKeyConstraint(['destination'], ['address.uid'], ),
    sa.ForeignKeyConstraint(['origin'], ['address.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('worker',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('passhash', sa.String(), nullable=True),
    sa.Column('license_uid', sa.String(), nullable=False),
    sa.Column('license_type', sa.String(), nullable=False),
    sa.Column('addr_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addr_uid'], ['address.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_worker_email'), 'worker', ['email'], unique=True)
    op.create_index(op.f('ix_worker_license_uid'), 'worker', ['license_uid'], unique=True)
    op.create_table('offer',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('proposa_uid', sa.Integer(), nullable=False),
    sa.Column('worker_uid', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['proposa_uid'], ['proposal.uid'], ),
    sa.ForeignKeyConstraint(['worker_uid'], ['worker.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('propos_item_relat',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('proposa_uid', sa.Integer(), nullable=False),
    sa.Column('item_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_uid'], ['item.uid'], ),
    sa.ForeignKeyConstraint(['proposa_uid'], ['proposal.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('vehicle',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=24), nullable=False),
    sa.Column('brand', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('worker_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_uid'], ['worker.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_vehicle_license'), 'vehicle', ['license'], unique=True)
    op.create_table('worker_addr_relat',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('worker_uid', sa.Integer(), nullable=False),
    sa.Column('address_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_uid'], ['address.uid'], ),
    sa.ForeignKeyConstraint(['worker_uid'], ['worker.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('job',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('proposa_uid', sa.Integer(), nullable=False),
    sa.Column('offer_uid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_uid'], ['offer.uid'], ),
    sa.ForeignKeyConstraint(['proposa_uid'], ['proposal.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('worker_addr_relat')
    op.drop_index(op.f('ix_vehicle_license'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_table('propos_item_relat')
    op.drop_table('offer')
    op.drop_index(op.f('ix_worker_license_uid'), table_name='worker')
    op.drop_index(op.f('ix_worker_email'), table_name='worker')
    op.drop_table('worker')
    op.drop_table('proposal')
    op.drop_table('compan_addr_relat')
    op.drop_table('item')
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_index(op.f('ix_company_cnpj'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_address_postcode'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
